### ISSUE TITLE
when limits or requests are both set to 1m or 1Mi they get rewritten as 0, and the pod fails to start

### ISSUE THREAD

**Issue by josephtingiris** [openshift/cluster-resource-override-admission-operator#81]
This is my cr, note limitCPUToMemoryPercent isn't set ...

```yaml
apiVersion: operator.autoscaling.openshift.io/v1
kind: ClusterResourceOverride
metadata:
    name: cluster
spec:
  podResourceOverride:
    spec:
      cpuRequestToLimitPercent: 5
      memoryRequestToLimitPercent: 5
      #limitCPUToMemoryPercent: 200
```

Example of get pod after deploying with the resource override operator enabled for this namespace ...

```yaml
    Args:
      cp -rpf /tmp/Sample_data /tmp/sampledata;
    Limits:
      cpu:     0
      memory:  0
    Requests:
      cpu:        0
      memory:     0
    Environment:  <none>
    Mounts:
      /tmp/sampledata from sampledata-pv-volume (rw)
```

Events with namespace labeled ...

```
Warning  FailedCreate  20m    job-controller  Error creating: Pod "sample-data-job-bxxl9" is invalid: [spec.containers[0].resources.requests: Invalid value: "1m": must be less than or equal to cpu limit, spec.containers[0].resources.requests: Invalid value: "1Mi": must be less than or equal to memory limit]
```

... no issues deploying 1m/1Mi limits without the override operator in the middle.
